config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  # root "users#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get 'my-dashboard', to: 'users#my_dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'store' => 'product#index'
  get 'store/product/:id' => 'product#show', as: 'product'
  post 'user/purchase' => 'users#purchase', as: 'purchase'
  get 'store/product/:id/buy' => 'product#buy', as: 'buy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :purchases
  after_create :connect_bitcoin_account
  after_create :get_profile_pic
  attr_accessor :activity_distance, :goal_distance, :baseline
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:runkeeper], :authentication_keys => [:uid]

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = "#{auth.uid}@runkeeper.com"
     user.password = Devise.friendly_token[0,20]
     user.birthday = auth.extra.raw_info.birthday
     user.name = auth.info.name
     user.auth_token = auth.credentials.token
   end
  end

  def connect_bitcoin_account
    account = BtcAccount.create_account(self.email)
    self.bitcoin_address = account[:address]
    self.account_id = account[:account_id]
    self.save
  end

  def calculate_balance
    balance = 0
    goals.each do |goal|
      if goal.achieved
        balance += goal.amount
      else
        balance -= goal.amount
      end
    end
    purchases.each{|purchase| balance -= purchase.amount}
    balance
  end

  def get_profile_pic
    self.pic_url = GraphAPI.get_rk_profile_pic(self)
    save!
  end

  def import_events
    import_running_events
    import_cycling_events
  end

  def import_running_events
    import_events_for_type(EventType.find_by_code('RUN').id, GraphAPI.get_running_activity_items(self))
  end

  def import_cycling_events
    import_events_for_type(EventType.find_by_code('CYC').id, GraphAPI.get_cycling_activity_items(self))
  end

  def next_goal
    next_run_goal
  end

  def next_run_goal
    calculate_next_goal(EventType.find_by_code('RUN').id)
  end

  def next_cycle_goal
    calculate_next_goal(EventType.find_by_code('CYC').id)
  end


  def goals
    events.map(&:goal).compact
  end

  private

  def import_events_for_type(event_type_id, activities)
    current_events = Event.where(user_id: self.id).map(&:uuid)
    new_activities = activities.select{|activity| !current_events.include?(activity['uri'][19..27])}
    new_activities.each do |activity|
      events = Event.where(user_id: self.id).where(event_type_id: event_type_id)
      total_distance = events.map{|event| event.data.to_f}.inject(:+)
      @baseline = total_distance ?  total_distance / events.length : 1
      @goal_distance = baseline * 1.1
      @activity_distance = activity["total_distance"] * 0.000621371
      goal = nil
      if paid
        goal = Goal.create!(goal_hash)
        if goal.achieved
          # BtcTransfer.reward_user(self, goal.amount)
        elsif goal.amount > 0
          balance = BtcAccount.get_balance_for_user(self).to_i
          penalty = goal.amount < balance ? goal.amount : balance
          # BtcTransfer.penalize_user(self, penalty)
        end
      end      
      Event.create!(user_id: self.id, event_type_id: event_type_id, data: "#{activity_distance}", goal_id: goal.try(:id), uuid: activity['uri'][19..27], event_date: activity.start_time)
    end
  end

  def calculate_next_goal(event_type_id)
    events = Event.where(user_id: self.id).where(event_type_id: event_type_id)
    total_distance = events.map{|event| event.data.to_f}.inject(:+)
    baseline = total_distance ?  total_distance / events.length : 1
    (baseline * 1.1).round(2)
  end

  def goal_hash
    if activity_distance > goal_distance
      {achieved: true, amount: bonus_amount}
    elsif activity_distance > (baseline * 0.75)
      {achieved: false, amount: 0}
    else
      {achieved: false, amount: 120000}
    end
  end

  def bonus_amount
    difference = activity_distance - goal_distance
    percent_above_goal = difference / baseline
    multiplier = percent_above_goal + 1
    bonus = multiplier > 1.5 ? 1.5 : multiplier
    120000 * bonus
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def runkeeper
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      @user.import_events
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Runkeeper") if is_navigational_format?
    else
      session["devise.runkeeper_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def my_dashboard
    current_user.import_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => 500,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
      if charge.paid
        current_user.paid = true
        current_user.save
      end
      redirect_to my_dashboard_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :bitcoin_address, :account_id, :name, :birthday, :provider, :uid, :auth_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_activity_feed.html.erb
<div class='col-md-12 container-block' style='min-height: 46.9em; max-height: 46.9em;'>
  <header>
    <h3>Activity Feed</h3>
  </header>
  <div class='row activity-row'>
    <div class='col-md-2 activity-title'>
      <p>Activity</p>
    </div>
    <div class='col-md-4 activity-title'>
      <p>Distance</p>
    </div>
    <div class='col-md-2 activity-title'>
      <p>Date</p>
    </div>
    <div class='col-md-2 activity-title'>
      <p>Earnings</p>
    </div>
    <div class='col-md-2 activity-title'>
      <p>Trend</p>
    </div>
  </div>
  <div style='min-height: 38.9em; max-height: 38.9em; overflow:scroll'>
    <% current_user.events.sort_by{|evt| evt.event_date.to_date}.reverse.each do |event| %>
    <div class='row' style='padding-top:1.5em'>
      <div class='col-md-2'>
        <% if event.event_type.code == "CYC" %>
          <%= image_tag 'biking.png', style: "height: 30px"  %>
        <% else %>
          <%= image_tag 'runner.png', style: "height: 30px"  %>
        <% end %>
      </div>
      <div class='col-md-4'>
        <p><%= event.data.to_f.round(3) %> miles</p>
      </div>
      <div class='col-md-2'>
        <p><%= event.event_date.to_date.strftime("%b %e, %Y") %></p>
      </div>
      <div class='col-md-2'>
        <p class="amount"><%= event.goal ? (number_with_delimiter(event.goal.amount, delimeter: ',') || 'Signup For Pro') : '' %></p>
      </div>
      <div class='col-md-2'>
        <% if event.goal  %>
          <% if event.goal.achieved %>
          <i class='fa fa-arrow-up' style="color:green;"></i>
          <% elsif event.goal.amount > 0 %>
          <i class='fa fa-arrow-down'style="color:red"></i>
          <% else %>
          <i class='fa fa-minus'></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <hr>
    <% end %>
  </div>
</div>

app/views/users/_current_balance.html.erb
<div class='col-md-12 container-block text-center' style='margin-bottom:1em'>
  <header style='border-bottom: thin solid lightgray'>
    <h3>Current Balance</h3>
  </header>
  <% if current_user.paid %>
    <p class='dashboard-numbers' style='padding-bottom:0'><%= number_with_delimiter(current_user.calculate_balance, delimeter: ',') %></p>
    <p class='dashboard-numbers' style='padding:0'><i class='fa fa-btc' style='color: #FF9900'></i> satoshi</p>
  <% else %>
    <%= form_tag purchase_path, class:'stripe-form' do %>
      <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
       data-key="<%= ENV['STRIPE_TEST_PUBLISH_KEY'] %>"
       data-description="$5.00"
       data-amount="500">
       </script>
       <script type="text/javascript">
         $(".stripe-button-el span").text("Go Pro to Unlock");
       </script>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_next_goal.html.erb
<div class='col-md-12 container-block text-center' style='margin-bottom:1em'>
  <header style='border-bottom: thin solid lightgray'>
    <h3>Next Goals</h3>
  </header>
  <p class='dashboard-numbers'><%= image_tag 'runner.png', style: 'height: 30px' %> <%= current_user.next_run_goal %> Miles</p>
  <p class='dashboard-numbers'><%= image_tag 'biking.png', style: 'height: 30px' %> <%= current_user.next_cycle_goal %> Miles</p>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/my_dashboard.html.erb
<div class='col-md-12'>
  <div class='col-md-3 same-height'>
    <div class='col-md-12 container-block' style='margin-bottom:1em'>
      <div class='col-md-8 col-md-offset-2' style='padding:1em'>
        <%= image_tag current_user.pic_url, class: 'img-circle' %>
      </div>
      <div class='col-md-12 text-center'>
        <h3><%= current_user.name %></h3>
      </div>
    </div>
    <%= render 'current_balance' %>
    <%= render 'next_goal' %>
  </div>
  <div class='col-md-9 same-height'>
    <%= render 'activity_feed' %>
  </div>
</div>
<div class='col-md-12'>
  <div class='col-md-6'>
    <div class='col-md-12 container-block'>
      <h3>Run Forest Run</h3>
      <%= line_chart EventGraph.running_graph(current_user) %>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='col-md-12 container-block'>
      <h3>Peddle to the Metal</h3>
      <%= line_chart EventGraph.biking_graph(current_user) %>
    </div>
  </div>
  <div class='col-md-12' style='margin-top:1em'>
    <div class='col-md-12 container-block'>
      <h3>Earnings by Activity</h3>
      <%= line_chart EventGraph.earnings_graph(current_user), colors: ["#FF9900"] %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>