config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  # root "users#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get 'my-dashboard', to: 'users#my_dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'store' => 'product#index'
  get 'store/product/:id' => 'product#show', as: 'product'
  post 'user/purchase' => 'users#purchase', as: 'purchase'
  get 'store/product/:id/buy' => 'product#buy', as: 'buy'
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :grab_product, only: [:buy, :show]

  # index
  def index
    @products = Product.all
  end
  # show
  def show
  end

  def buy
    sat_price = CurrencyConverter.usd_to_satoshi(@product.price)
    if BtcAccount.get_balance_for_user(current_user).to_i >= sat_price
      BtcTransfer.penalize_user(current_user, sat_price)
      Purchase.create(user_id: current_user.id, amount: sat_price.to_i)
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  private

  def grab_product
    @product = Product.find(params[:id])
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/_masonry_products.html.erb
<div class='container'>
  <div class="row grid">
    <% @products.each do |product| %>
      <div class="col-md-3 grid-item" style='margin-bottom:1em;'>
        <div class='col-md-12 product-image' style='position:relative'>
          <%= link_to image_tag(product.picture, style: 'border: thin solid lightgray'), product_path(product) %>
          <div class='product-info'>
            <div class='text-center'>
              <div style='background-color:white'>
                <h4 class='upcase'><%= link_to product.title, product_path(product) %></h4>
                <h5 style='font-size:1.5em'><%= number_with_delimiter(CurrencyConverter.usd_to_satoshi(product.price), delimiter: ',') %> <i class='fa fa-btc' style='font-size:1em; color: #FF9900'> satoshi</i></h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script src="https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.min.js">
  productMasonry = function(){
    $('.grid').masonry({
      itemSelector: '.grid-item'
      // columnWidth: 25
    });
  }
  $(document).on('turbolinks:load', productMasonry);
</script>

app/views/product/index.html.erb
<div class='container'>
  <div class='col-md-12 text-center'>
    <h2 class='upcase'>Welcome to the BitStore</h2>
    <h3>Current Balance: <%= number_with_delimiter(current_user.calculate_balance, delimeter: ',') %> <i class='fa fa-btc' style='color:#FF9900'></i> satoshi </h3>
  </div>
</div>
<%= render 'masonry_products' %>

app/views/product/show.html.erb
<div class="col-md-12">
  <div class='col-md-4'>
    <div class='col-md-12'>
      <%= image_tag(@product.picture) %>
    </div>
  </div>
  <div class='col-md-8'>
    <div class='col-md-12 container-block'>
      <div class="col-md-8">
        <h4 style='color:#2CC8D6'>Product Name</h4>
        <hr>
        <h3><%= @product.title %></h3>
      </div>
      <div class='col-md-4'>
        <h4 style='color:#2CC8D6'>Price</h4>
        <hr>
        <h3><%= number_with_delimiter(CurrencyConverter.usd_to_satoshi(@product.price), delimiter: ',') %> <i class='fa fa-btc' style='color:#FF9900'></i> satoshi</h3>
      </div>
      <div class="col-md-12">
        <h4 style='color:#2CC8D6'>Description</h4>
        <hr>
        <h3><%= @product.description %></h3>
      </div>
      <div class="col-md-12" style='padding:1em'>
        <button type="button" class="swole-button" data-toggle="modal" data-target="#myModal">
          Buy now
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= @product.title %></h4>
      </div>
      <div style='padding: 2.5em 0'>
        <div class='col-md-12 text-center'>
          <p style='font-size: 1.5em'><%= BtcAccount.get_balance_for_user(current_user).to_i %>
          - <%= CurrencyConverter.usd_to_satoshi(@product.price) %>
          = <%= (BtcAccount.get_balance_for_user(current_user).to_i - CurrencyConverter.usd_to_satoshi(@product.price)) %></p>
        </div>
        <% if BtcAccount.get_balance_for_user(current_user).to_i < CurrencyConverter.usd_to_satoshi(@product.price) %>
        <div class='col-md-12 text-center'>
          <h3>You do not have enough satoshi yet <i class='fa fa-frown-o'></i></h3>
        </div>
        <% else %>
        <div class='col-md-12 text-center'>
          <h3>Whoo hoo! Get it while it's hot! <i class='fa fa-smile-o'></i></h3>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <% if BtcAccount.get_balance_for_user(current_user).to_i >= CurrencyConverter.usd_to_satoshi(@product.price) %>
          <%= button_to 'Buy', buy_path(@product), method: :get, class: 'swole-button' %>
        <% else %>
          <%= button_to 'Buy', buy_path(@product), method: :get, class: 'swole-button', disabled: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>