config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  # root "users#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get 'my-dashboard', to: 'users#my_dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'store' => 'product#index'
  get 'store/product/:id' => 'product#show', as: 'product'
  post 'user/purchase' => 'users#purchase', as: 'purchase'
  get 'store/product/:id/buy' => 'product#buy', as: 'buy'
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-6">
        <p>swoleBit <i class="fa fa-copyright"></i></p>
      </div>
      <div class="col-md-6">
        <p class="pull-right">If you enjoy BitCoin click <a href="https://en.bitcoin.it/wiki/Main_Page" target="_blank">here</a> to learn more.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to 'swoleBIT', root_path, class: 'navbar-brand' %>
      <a class="navbar-brand" style='padding:5px' href="#"><%= image_tag 'sb-logo.png', style: 'height:40px', class: 'img-responsive' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'My Dashboard', my_dashboard_path %></li>
        <li><%= link_to 'BitStore', store_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Hi #{current_user.name}", "#" %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swole</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,300,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <% if alert  %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navbar' unless @disable_nav %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>